development:
  adapter: mysql2
  database: grape_api
  user: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: grape_api_test
  user: root
  password:
  pool: 5
  timeout: 5000